version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_NAME=veterinaria_db
      - DB_USER=postgres
      - DB_PASSWORD=Flgonta1995*
      - DB_HOST=host.docker.internal
      - JWT_SECRET=secretKey1234
      - PORT=5000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
      - ./uploads:/app/backend/uploads  # Carpeta de archivos persistente
    networks:
      - vet-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    networks:
      - vet-network
    depends_on:
      - backend

networks:
  vet-network:
    driver: bridge